### ISSUE TITLE
Main configuration file missing in installation package 

### ISSUE THREAD

**Issue by steinhauserdominik** [Inconspicuous-Backup-Solutions-Dev-Team/Inconspicuous-Backup-Service#1]
The configuration file in Inconspicuous-Backup-Service/conf/README.md under Basic Configuration is unavailable.

**Comment by chris109b** [comment]
#

**Comment by chris109b** [comment]
Created file in commit 7bdb87f386972c52689bba4c077aeb4863a47f43
