### ISSUE TITLE
Auto directory creation failed

### ISSUE THREAD

**Issue by steinhauserdominik** [Inconspicuous-Backup-Solutions-Dev-Team/Inconspicuous-Backup-Service#10]
If you run the script with ./backup backup it reports an error that the directory /tmp/inconspicuous_backup_service  is missing on host. You have to create this directory by hand than the error is fixed but this is not user-friendly.

**Comment by chris109b** [comment]
Fixet with commit 5589b9323ab39f2b655dfddd3e950f16a1851216
