### ISSUE TITLE
Unclear directory creation

### ISSUE THREAD

**Issue by steinhauserdominik** [Inconspicuous-Backup-Solutions-Dev-Team/Inconspicuous-Backup-Service#11]
If you make a backup from the database, the backup is saved in "mnt/first_level_backup_storage/192_168_199_170/tmp/inconspicuous_backup_service/inconspicuous_backup_service/". You don´t need the second inconspicuous_backup_service directory.

**Comment by chris109b** [comment]
Fixed with commit 5589b9323ab39f2b655dfddd3e950f16a1851216
