### ISSUE TITLE
File path for the symbolic link is wrong

### ISSUE THREAD

**Issue by steinhauserdominik** [Inconspicuous-Backup-Solutions-Dev-Team/Inconspicuous-Backup-Service#5]
The createing of a symbolic link which stays in Inconspicuous-Backup-Service/conf/README.md is, is not makeable because the path is not right. The right path is "/opt/Inconspicuous-Backup-Service/conf/jobs/".

**Comment by chris109b** [comment]
Actually, if you follow the instructions starting from main README file, the correct path would be "/opt/inconspicuous_backup_service/conf/jobs/", because it says:
> Download the package and extract it to "/opt/inconspicuous_backup_service"
